use std::path::PathBuf;
use std::sync::Arc;

use async_trait::async_trait;
use pi_domain::contracts::OverrideStore;
use pi_domain::error::DomainError;

/// Text of override file (§12.1): mapping public service to bind address.
pub(crate) fn override_yaml(
    service: &str,
    bind: &str,
    host_port: u16,
    container_port: u16,
) -> String {
    format!(
        "# generated by pi - do not edit\nservices:\n  {service}:\n    ports:\n      - \"{bind}:{host_port}:{container_port}\"\n"
    )
}

pub struct FsOverrideStore {
    dir: PathBuf,
}

impl FsOverrideStore {
    pub fn new(dir: PathBuf) -> Arc<FsOverrideStore> {
        Arc::new(FsOverrideStore { dir })
    }
}

#[async_trait]
impl OverrideStore for FsOverrideStore {
    fn path(&self, project: &str) -> PathBuf {
        self.dir.join(format!("{project}.yml"))
    }

    async fn write(
        &self,
        project: &str,
        service: &str,
        bind: &str,
        host_port: u16,
        container_port: u16,
    ) -> Result<PathBuf, DomainError> {
        let io_err = |e: std::io::Error| DomainError::Storage(format!("override write: {e}"));
        tokio::fs::create_dir_all(&self.dir).await.map_err(io_err)?;
        let path = self.dir.join(format!("{project}.yml"));
        tokio::fs::write(&path, override_yaml(service, bind, host_port, container_port))
            .await
            .map_err(io_err)?;
        Ok(path)
    }

    async fn remove(&self, project: &str) -> Result<(), DomainError> {
        let io_err = |e: std::io::Error| DomainError::Storage(format!("override remove: {e}"));
        match tokio::fs::remove_file(self.dir.join(format!("{project}.yml"))).await {
            Ok(()) => Ok(()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(io_err(e)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn yaml_maps_bind_host_port_to_container_port() {
        let loopback = override_yaml("web", "127.0.0.1", 8000, 3000);
        assert_eq!(
            loopback,
            "# generated by pi - do not edit\nservices:\n  web:\n    ports:\n      - \"127.0.0.1:8000:3000\"\n"
        );
        let lan = override_yaml("web", "0.0.0.0", 8000, 3000);
        assert!(lan.contains("\"0.0.0.0:8000:3000\""));
    }

    #[tokio::test]
    async fn write_creates_file_in_overrides_dir() {
        let dir = tempfile::tempdir().unwrap();
        let store = FsOverrideStore::new(dir.path().join("overrides"));
        let path = store
            .write("rateme", "web", "127.0.0.1", 8000, 3000)
            .await
            .unwrap();
        assert_eq!(path, dir.path().join("overrides").join("rateme.yml"));
        let content = tokio::fs::read_to_string(&path).await.unwrap();
        assert!(content.contains("127.0.0.1:8000:3000"));
    }
}
